# Project information
site_name: Polymesh Developers Portal
site_url: https://developer.polymesh.live
site_description: Documentation for Polymesh

# Repository
repo_name: PolymathNetwork/Polymesh
repo_url: https://github.com/PolymathNetwork/polymesh
edit_uri: ""

nav: 
    - Home: index.md
    - Getting Started:
      - Pillars: pillars.md
      - Architecture: architecture.md
      - DeFi: defi.md
      - Alcyone Public Testnet: testnet.md
    - Polymesh Primitives:
      - Identity: identity.md
      - Customer Due Diligence: cdd.md
      - Confidential Identity: confidential_identity.md
      - Authorisations: authorisations.md
      - Assets: assets.md
      - Compliance: compliance.md
      - Settlement: settlement.md
      - Corporate Actions: corporate_actions.md
      - Smart Extensions: smart_extensions.md
    - Polymesh Network:
      - POLYX Token: polyx.md
      - POLY to POLYX Bridge: bridge.md
      - Fees: fees.md
      - Permissioned Roles: permissioned_roles.md
      - Governance: governance.md
      - Tokenomics: tokenomics.md
      - Consensus: consensus.md
    - Contribute:
      - Grants: grants.md
      - Bug Bounty: bug_bounty.md
      - Alcyone Testnet: testnet.md
    - Future Development:
      - Confidential Assets: confidential_assets.md
      - Smart Contracts: smart_contracts.md
      - Asset Statistics: statistics.md
    - External Resources: resources.md
    - Glossary: glossary.md

theme:
  name: material

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  #features:
    #- tabs
    #- instant
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: logo