# Project information
site_name: Polymesh
site_url: https://docs.polymesh.live
site_description: >-
  Documentation for Polymesh

# Repository
repo_name: PolymathNetwork/Polymesh
repo_url: https://github.com/PolymathNetwork/polymesh
edit_uri: ""

nav:
    - Aldebaran Network: 
      - Running A Node: about.md
      - dApps: about.md
    - POLYX:
      - Transaction Fees: about.md
      - Protocol Fees: about.md
      - Identity and Key Balances: about.md
      - POLY to POLYX Bridge: poly-bridge.md
    - Identity:
      - Key Management: about.md
      - Access Control: about.md
      - Multisig: about.md
      - CDD Process: about.md
      - Scope Labels: about.md
    - Assets:
      - Asset Lifecycle: about.md
      - Issuance / Redemption: about.md
      - Portfolios: about.md
    - Compliance:
      - Claims: about.md
      - Compliance Rules: about.md
    - Custody:
      - Custodians: about.md      
    - Settlement:
      - Venues, Instructions and Legs: about.md
      - Settlement Engine: about.md
    - Corporate Actions:
      - Funding: about.md
      - Dividends: about.md
      - Ballots: about.md
    - Governance:
      - Polymesh Improvement Proposals: about.md
      - Token Holder Proposals: about.md
      - Committees: about.md
      - Network Reserve: about.md
    - Smart Extensions:
      - Managing and Deploying Extensions: about.md
      - Count Transfer Manager: about.md
      - Percentage Transfer Manager: about.md
    - Consensus:
      - Permissioned Operators: about.md
      - Staking: about.md
      - Rewards / Fines: about.md

theme:
  name: material

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  #features:
    #- tabs
    #- instant
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: logo