# Project information
site_name: Polymesh Developers Portal
site_url: https://developers.polymesh.live
site_description: Documentation for Polymesh

# Repository
repo_name: PolymathNetwork/Polymesh
repo_url: https://github.com/PolymathNetwork/polymesh
edit_uri: ""

nav:
    - Getting Started:
      - Home: index.md
      - Architecture: architecture.md
      - Alcyone Public Testnet: testnet.md
    - Network:
      - POLYX Token: polyx.md
      - POLY to POLYX Bridge: bridge.md
      - Fees: fees.md
      - Permissioned Roles: permissioned_roles.md
      - Governance: governance.md
      - Tokenomics: tokenomics.md
      - Consensus: consensus.md
    - Primitives:
      - Identity: identity.md
      - Customer Due Diligence: cdd.md
      - Confidential Identity: confidential_identity.md
      - Authorisations: authorisations.md
      - Assets: assets.md        
      - Portfolios and Custody: portfolios_custody.md
      - Compliance: compliance.md
      - Settlement: settlement.md
      - Corporate Actions: corporate_actions.md
      - Smart Extensions: smart_extensions.md
    - Contribute:
      - Grants: grants.md
      - Bug Bounty: bug_bounty.md
    - Future Development:
      - Confidential Assets: confidential_assets.md
      - Smart Contracts: smart_contracts.md
      - Statistics Engine: statistics.md
    - Resources:
      - Resources: resources.md
    - Glossary:
      - Glossary: glossary.md

theme:
  name: material

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - tabs
    - instant
    - navigation.expand: true
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: logo

  markdown_extensions:
    - toc:
        permalink: true
