# Project information
site_name: Polymesh
site_url: https://developer.polymesh.live
site_description: >-
  Documentation for Polymesh

# Repository
repo_name: PolymathNetwork/Polymesh
repo_url: https://github.com/PolymathNetwork/polymesh
edit_uri: ""

nav:
    - Polymesh Overview:
      - Architecture: architecture.md
      - Timeline: timeline.md
      - Technology: technology.md
    - Alcyone Public Testnet: 
      - Running A Node: node.md
      - dApps: dapps.md
    - POLYX:
      - Transaction Fees: transaction_fees.md
      - Protocol Fees: protocol_fees.md
      - POLY to POLYX Bridge: poly_bridge.md
      - Treasury: treasury.md
    - Identity:
      - Key Management: key_management.md
      - Permissions: permissions.md
      - Multisig: multisig.md
      - CDD Process: cdd.md
      - Portfolios: portfolios.md
    - Confidential Identity:
      - Overview: ci_overview.md
      - Entities and Identities: entities.md
      - Identities and Assets: scope_labels.md
    - Authorisations:
      - Overview: auth_overview.md
    - Assets:
      - Overview: assets.md
      - Issuance: issuance.md
    - Compliance:
      - Claims: claims.md
      - Compliance Rules: rules.md
    - Settlement:
      - Venues, Instructions and Legs: settlement.md
      - Settlement Engine: settlement_engine.md
      - Security Token Offerings: stos.md
    - Corporate Actions:
      - Overview: ca_overview.md
      - Capital Distributions: cap_distribution.md
      - Corporate Ballots: ballots.md
    - Governance:
      - Overview: gov_overview.md
      - Polymesh Improvement Proposals: pips.md
      - Signalling: signalling.md
      - Committees: committees.md
      - Governance Council: gov_council.md
    - Smart Extensions:
      - Managing and Deploying Extensions: smart_extensions.md
      - Count Transfer Manager: ctm.md
      - Percentage Transfer Manager: ptm.md
    - Consensus:
      - Permissioned Operators: operators.md
      - Staking: staking.md
      - Rewards / Fines: tokenomics.md

theme:
  name: material

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  #features:
    #- tabs
    #- instant
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: logo