name: Publish docs

on: push
  # push:
  #   branches:
  #     - master

jobs:
  docs:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout current code
      uses: actions/checkout@v2
    - name: Install dependencies
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
      run: pip install mkdocs mkdocs-material
    - name: Build static docs
      run: mkdocs build
    - name: Publish docs to Cloudflare workers
      uses: cloudflare/wrangler-action@1.3.0
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
        workingDirectory: 'Polymesh'
      env:
        CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
