name: Publish docs

on:
  push:
    branches:
      - master

jobs:
  docs:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout current code
      uses: actions/checkout@v2
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Install mkdocs and our mkdocs theme
      run: pip install mkdocs==1.1.2 mkdocs-material==5.4.0
    - name: Build static docs
      run: mkdocs build
      working-directory: ./Polymesh
